name: fightclub
description: Beat the enemy
publish_to: 'none'
version: 1.1.2+12
environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  in_app_review: ^2.0.9
  shared_preferences: ^2.2.3
  url_strategy: ^0.2.0

dev_dependencies:
  carapacik_lints: ^1.8.1
  #flutter_launcher_icons: ^0.13.1
  #flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - google_fonts/

flutter_launcher_icons:
  image_path: "assets/app/ic_logo.png"
  android: true
  adaptive_icon_background: "assets/app/ic_background.png"
  adaptive_icon_foreground: "assets/app/ic_foreground.png"
  min_sdk_android: 24
  ios: true
  remove_alpha_ios: true
  macos:
    generate: true
  windows:
    generate: true

flutter_native_splash:
  color: "#D5DEF0"
  image: "assets/app/ic_foreground.png"
  android: true
  ios: true
  web: true
