name: fightclub
description: Beat the enemy
publish_to: 'none'
version: 1.0.7+8

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.3.1
  in_app_review: ^2.0.4
  shared_preferences: ^2.0.13
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_launcher_icons_maker: ^0.10.2
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

flutter_icons:
  android: true
  ios: true
  web: true
  windows: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - google_fonts/