name: fightclub
description: Beat the enemy
publish_to: 'none'
version: 1.1.1+10

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  in_app_review: ^2.0.6
  shared_preferences: ^2.0.17
  url_strategy: ^0.2.0

dev_dependencies:
  carapacik_lints: ^1.3.1
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - google_fonts/

flutter_icons:
  image_path: 'assets/ic_logo.png'
  adaptive_icon_background: 'assets/ic_background.png'
  adaptive_icon_foreground: 'assets/ic_foreground.png'
  remove_alpha_ios: true
  remove_alpha_macos: true
  android: true
  ios: true
  linux: true
  macos: true
  web: true
  windows: true
