name: fightclub
description: Beat the enemy and defend yourself
publish_to: 'none'
version: 1.4.0+23

environment:
  sdk: ^3.13.0
  flutter: '>=3.47.0'

dependencies:
  flutter:
    sdk: flutter
  in_app_review: ^2.0.12
  material_ui: ^1.0.1
  shared_preferences: ^2.5.5

dev_dependencies:
  carapacik_lints: ^3.13.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.8
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  fonts:
    - family: Press Start 2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
  licenses:
    - assets/fonts/OFL.txt

flutter_launcher_icons:
  image_path: assets/app/ic_logo.png
  android: true
  adaptive_icon_background: assets/app/ic_background.png
  adaptive_icon_foreground: assets/app/ic_foreground.png
  min_sdk_android: 24
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: assets/app/ic_logo.png
    background_color: '#D5DEF0'
    theme_color: '#D5DEF0'
  macos:
    generate: true
    image_path: assets/app/ic_logo.png
  windows:
    generate: true
    image_path: assets/app/ic_logo.png
    icon_size: 256

flutter_native_splash:
  color: '#D5DEF0'
  image: assets/app/ic_foreground.png
  android: true
  ios: true
  web: true
  android_12:
    color: '#D5DEF0'
    image: assets/app/ic_foreground.png
