name: fightclub
description: Beat the enemy

publish_to: 'none'

version: 1.0.3+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  in_app_review: ^2.0.3
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  shared_preferences: ^2.0.8
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  rename: ^1.3.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - google_fonts/
    - assets/icons/
    - assets/images/